name: Deploy Vite to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build
        env:
          VITE_SUPABASE_URL: https://hhitpcwescauzvfcyylk.supabase.co
          VITE_SUPABASE_ANON_KEY: sb_publishable_XXcb6-odYCf7z2ZFaIC4tA_5bbv_gFj

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/configure-pages@v4

      - id: deployment
        uses: actions/deploy-pages@v4
